---
title: "02A_Historical Fitting_NEE"
author: "Nia Bartolucci; Cameron Reimer; Kangjoon Cho; Zhenpeng Zuo"
date: "3/25/2021"
output: html_document
---

```{r}
## Package check and load

#install.packages("tidyverse")
#install.packages("readr")
#remotes::install_github("EcoForecast/ecoforecastR",force=TRUE)
library(tidyverse)
library(readr)
library(rjags)
library(daymetr)
library(ecoforecastR)

```

```{r}
# If you need run data download
###source('01A_Targetdownload.R')

# definition for PATH
basePath <- getwd() 
graphPath <- paste0(basePath,"/graph/")
dataPath <- paste0(basePath,"/data/")

# load the data file [30 min Target data]
loadFilename <- sprintf("%s.Rdata","Target_30min")
loadFilename <- paste(dataPath, loadFilename, sep="", collapse = NULL)
load(file = loadFilename)

# load the data file [daily Target data]
loadFilename <- sprintf("%s.Rdata","Target_daily")
loadFilename <- paste(dataPath, loadFilename, sep="", collapse = NULL)
load(file = loadFilename)

# define site names
site_names <- c("BART","KONZ","OSBS","SRER")

```

```{r}

#Subset Data 

Target_30min_BART = subset(Target_30min, siteID == 'BART')
Target_30min_KONZ = subset(Target_30min, siteID == 'KONZ')
Target_30min_OSBS = subset(Target_30min, siteID == 'OSBS')
Target_30min_SRER = subset(Target_30min, siteID == 'SRER')

time_BART = as.Date(Target_30min_BART$time)
time_KONZ = as.Date(Target_30min_KONZ$time)
time_OSBS = as.Date(Target_30min_OSBS$time)
time_SRER = as.Date(Target_30min_SRER$time)

Target_daily_BART = subset(Target_daily, siteID == 'BART')
Target_daily_KONZ = subset(Target_daily, siteID == 'KONZ')
Target_daily_OSBS = subset(Target_daily, siteID == 'OSBS')
Target_daily_SRER = subset(Target_daily, siteID == 'SRER')

time_daily_BART = as.Date(Target_daily_BART$time)
time_daily_KONZ = as.Date(Target_daily_KONZ$time)
time_daily_OSBS = as.Date(Target_daily_OSBS$time)
time_daily_SRER = as.Date(Target_daily_SRER$time)

nee_BART = Target_30min_BART$nee
nee_KONZ = Target_30min_KONZ$nee
nee_OSBS = Target_30min_OSBS$nee
nee_SRER = Target_30min_SRER$nee

rm(Target_30min, Target_daily)

```

```{r}
RandomWalk = "
model{
  #### Data Model
  for(t in 1:n){
    y[t] ~ dnorm(x[t],tau_obs)
  }
  #### Process Model
  for(t in 2:n){
    x[t]~dnorm(x[t-1],tau_add)
  }
  #### Priors
  x[1] ~ dnorm(x_ic,tau_ic)
  tau_obs ~ dgamma(a_obs,r_obs)
  tau_add ~ dgamma(a_add,r_add)
}
"
```

```{r}
#Set Initial Conditions 
x_ic_nee = 1
tau_ic_nee = 10 

data_nee_BART <- list(y=nee_BART,n=length(nee_BART),x_ic= x_ic_nee,tau_ic=tau_ic_nee, a_obs=1,r_obs=1,a_add=1,r_add=1)
data_nee_KONZ <- list(y=nee_KONZ,n=length(nee_KONZ),x_ic= x_ic_nee,tau_ic=tau_ic_nee, a_obs=1,r_obs=1,a_add=1,r_add=1)
data_nee_OSBS <- list(y=nee_OSBS,n=length(nee_OSBS),x_ic= x_ic_nee,tau_ic=tau_ic_nee, a_obs=1,r_obs=1,a_add=1,r_add=1)
data_nee_SRER <- list(y=nee_SRER,n=length(nee_SRER),x_ic= x_ic_nee,tau_ic=tau_ic_nee, a_obs=1,r_obs=1,a_add=1,r_add=1)
```

```{r}
#Set inits 

#NEE
nchain = 3
init_nee_BART <- list()
init_nee_KONZ <- list()
init_nee_OSBS <- list()
init_nee_SRER <- list()
y_BART = nee_BART 
y_KONZ = nee_KONZ
y_OSBS = nee_OSBS
y_SRER = nee_SRER
y_BART = na.omit(y_BART)
y_KONZ = na.omit(y_KONZ)
y_OSBS = na.omit(y_OSBS)
y_SRER = na.omit(y_SRER)
for(i in 1:nchain){
  y.samp = sample(y_BART,length(y_BART),replace=TRUE)
  init_nee_BART[[i]] <- list(tau_add=1/var(diff(y.samp)),tau_obs=5/var(y.samp))
  y.samp = sample(y_KONZ,length(y_KONZ),replace=TRUE)
  init_nee_KONZ[[i]] <- list(tau_add=1/var(diff(y.samp)),tau_obs=5/var(y.samp))
  y.samp = sample(y_OSBS,length(y_OSBS),replace=TRUE)
  init_nee_OSBS[[i]] <- list(tau_add=1/var(diff(y.samp)),tau_obs=5/var(y.samp))
  y.samp = sample(y_SRER,length(y_SRER),replace=TRUE)
  init_nee_SRER[[i]] <- list(tau_add=1/var(diff(y.samp)),tau_obs=5/var(y.samp))
}

rm(y_BART, y_KONZ, y_OSBS, y_SRER)
```


```{r}
#JAGS Model Runs

j.model_nee_BART   <- jags.model (file = textConnection(RandomWalk),
                             data = data_nee_BART,
                             inits = init_nee_BART,
                             n.chains = 3)
j.model_nee_KONZ   <- jags.model (file = textConnection(RandomWalk),
                             data = data_nee_KONZ,
                             inits = init_nee_KONZ,
                             n.chains = 3)
j.model_nee_OSBS   <- jags.model (file = textConnection(RandomWalk),
                             data = data_nee_OSBS,
                             inits = init_nee_OSBS,
                             n.chains = 3)
j.model_nee_SRER   <- jags.model (file = textConnection(RandomWalk),
                             data = data_nee_SRER,
                             inits = init_nee_SRER,
                             n.chains = 3)

```

```{r}
#MCMC diagnostics & Burn-in test
jags.out_nee_BART <- coda.samples (model = j.model_nee_BART,
                            variable.names = c("tau_add","tau_obs"),
                                n.iter = 5000)
jags.out_nee_KONZ <- coda.samples (model = j.model_nee_KONZ,
                            variable.names = c("tau_add","tau_obs"),
                                n.iter = 5000)
jags.out_nee_OSBS <- coda.samples (model = j.model_nee_OSBS,
                            variable.names = c("tau_add","tau_obs"),
                                n.iter = 5000)
jags.out_nee_SRER <- coda.samples (model = j.model_nee_SRER,
                            variable.names = c("tau_add","tau_obs"),
                                n.iter = 5000)

newFilename <- sprintf("%s.jpg","NEE_BART_traceplot")
newFilename <- paste(graphPath, newFilename, sep="", collapse = NULL)
jpeg(file = newFilename)
plot(jags.out_nee_BART)
dev.off()

newFilename <- sprintf("%s.jpg","NEE_KONZ_traceplot")
newFilename <- paste(graphPath, newFilename, sep="", collapse = NULL)
jpeg(file = newFilename)
plot(jags.out_nee_KONZ)
dev.off()

newFilename <- sprintf("%s.jpg","NEE_OSBS_traceplot")
newFilename <- paste(graphPath, newFilename, sep="", collapse = NULL)
jpeg(file = newFilename)
plot(jags.out_nee_OSBS)
dev.off()

newFilename <- sprintf("%s.jpg","NEE_SRER_traceplot")
newFilename <- paste(graphPath, newFilename, sep="", collapse = NULL)
jpeg(file = newFilename)
plot(jags.out_nee_SRER)
dev.off()
```

```{r}
# MCMC Diagnostics - BART/KONZ accept, OSBS/SRER rerun
newFilename <- sprintf("%s.jpg","NEE_BART_gelmanplot")
newFilename <- paste(graphPath, newFilename, sep="", collapse = NULL)
jpeg(file = newFilename)
BGR_BART <- gelman.plot(jags.out_nee_BART)
dev.off()

newFilename <- sprintf("%s.jpg","NEE_KONZ_gelmanplot")
newFilename <- paste(graphPath, newFilename, sep="", collapse = NULL)
jpeg(file = newFilename)
BGR_KONZ <- gelman.plot(jags.out_nee_KONZ)
dev.off()

newFilename <- sprintf("%s.jpg","NEE_OSBS_gelmanplot")
newFilename <- paste(graphPath, newFilename, sep="", collapse = NULL)
jpeg(file = newFilename)
BGR_OSBS <- gelman.plot(jags.out_nee_OSBS)
dev.off()

newFilename <- sprintf("%s.jpg","NEE_SRER_gelmanplot")
newFilename <- paste(graphPath, newFilename, sep="", collapse = NULL)
jpeg(file = newFilename)
BGR_SRER <- gelman.plot(jags.out_nee_SRER)
dev.off()

rm(BGR_BART, BGR_KONZ, BGR_OSBS, BGR_SRER)

gelman.diag(jags.out_nee_BART)
gelman.diag(jags.out_nee_KONZ)
gelman.diag(jags.out_nee_OSBS)
gelman.diag(jags.out_nee_SRER)

effectiveSize(jags.out_nee_BART)
effectiveSize(jags.out_nee_KONZ)
effectiveSize(jags.out_nee_OSBS)
effectiveSize(jags.out_nee_SRER)
```

```{r}
# rerun coda.samples

jags.out_nee_OSBS <- coda.samples (model = j.model_nee_OSBS,
                            variable.names = c("tau_add","tau_obs"),
                                n.iter = 5000)
jags.out_nee_SRER <- coda.samples (model = j.model_nee_SRER,
                            variable.names = c("tau_add","tau_obs"),
                                n.iter = 5000)
newFilename <- sprintf("%s.jpg","NEE_OSBS_traceplot_2nd")
newFilename <- paste(graphPath, newFilename, sep="", collapse = NULL)
jpeg(file = newFilename)
plot(jags.out_nee_OSBS)
dev.off()

newFilename <- sprintf("%s.jpg","NEE_SRER_traceplot_2nd")
newFilename <- paste(graphPath, newFilename, sep="", collapse = NULL)
jpeg(file = newFilename)
plot(jags.out_nee_SRER)
dev.off()

newFilename <- sprintf("%s.jpg","NEE_OSBS_gelmanplot_2nd")
newFilename <- paste(graphPath, newFilename, sep="", collapse = NULL)
jpeg(file = newFilename)
BGR_OSBS <- gelman.plot(jags.out_nee_OSBS)
dev.off()

newFilename <- sprintf("%s.jpg","NEE_SRER_gelmanplot_2nd")
newFilename <- paste(graphPath, newFilename, sep="", collapse = NULL)
jpeg(file = newFilename)
BGR_SRER <- gelman.plot(jags.out_nee_SRER)
dev.off()

gelman.diag(jags.out_nee_OSBS)
gelman.diag(jags.out_nee_SRER)

effectiveSize(jags.out_nee_OSBS)
effectiveSize(jags.out_nee_SRER)
```

```{r}
# rerun coda.samples

jags.out_nee_SRER <- coda.samples (model = j.model_nee_SRER,
                            variable.names = c("tau_add","tau_obs"),
                                n.iter = 5000)

newFilename <- sprintf("%s.jpg","NEE_SRER_traceplot_3rd")
newFilename <- paste(graphPath, newFilename, sep="", collapse = NULL)
jpeg(file = newFilename)
plot(jags.out_nee_SRER)
dev.off()

newFilename <- sprintf("%s.jpg","NEE_SRER_gelmanplot_3rd")
newFilename <- paste(graphPath, newFilename, sep="", collapse = NULL)
jpeg(file = newFilename)
BGR_SRER <- gelman.plot(jags.out_nee_SRER)
dev.off()

gelman.diag(jags.out_nee_SRER)

effectiveSize(jags.out_nee_SRER)
```

```{r}
# rerun coda.samples

jags.out_nee_SRER <- coda.samples (model = j.model_nee_SRER,
                            variable.names = c("tau_add","tau_obs"),
                                n.iter = 5000)

newFilename <- sprintf("%s.jpg","NEE_SRER_traceplot_4th")
newFilename <- paste(graphPath, newFilename, sep="", collapse = NULL)
jpeg(file = newFilename)
plot(jags.out_nee_SRER)
dev.off()

newFilename <- sprintf("%s.jpg","NEE_SRER_gelmanplot_4th")
newFilename <- paste(graphPath, newFilename, sep="", collapse = NULL)
jpeg(file = newFilename)
BGR_SRER <- gelman.plot(jags.out_nee_SRER)
dev.off()

gelman.diag(jags.out_nee_SRER)

effectiveSize(jags.out_nee_SRER)
```


```{r}
rm(jags.out_nee_BART, jags.out_nee_KONZ, jags.out_nee_OSBS, jags.out_nee_SRER)

# Generate 3000 post-burn-in samples and save output

newFilename <- sprintf("%s.Rdata", "NEE_BART_JAGS")
newFilename <- paste(dataPath, newFilename, sep="", collapse = NULL)
jags.burn_nee_BART <- coda.samples (model = j.model_nee_BART,
                            variable.names = c("x","tau_add","tau_obs"),
                                n.iter = 3000)

save(jags.burn_nee_BART, file = newFilename)
rm(jags.burn_nee_BART)

newFilename <- sprintf("%s.Rdata", "NEE_KONZ_JAGS")
newFilename <- paste(dataPath, newFilename, sep="", collapse = NULL)
jags.burn_nee_KONZ <- coda.samples (model = j.model_nee_KONZ,
                            variable.names = c("x","tau_add","tau_obs"),
                                n.iter = 3000)

save(jags.burn_nee_KONZ, file = newFilename)
rm(jags.burn_nee_KONZ)

newFilename <- sprintf("%s.Rdata", "NEE_OSBS_JAGS")
newFilename <- paste(dataPath, newFilename, sep="", collapse = NULL)
jags.burn_nee_OSBS <- coda.samples (model = j.model_nee_OSBS,
                            variable.names = c("x","tau_add","tau_obs"),
                                n.iter = 3000)
save(jags.burn_nee_OSBS, file = newFilename)
rm(jags.burn_nee_OSBS)

newFilename <- sprintf("%s.Rdata", "NEE_SRER_JAGS")
newFilename <- paste(dataPath, newFilename, sep="", collapse = NULL)
jags.burn_nee_SRER <- coda.samples (model = j.model_nee_SRER,
                            variable.names = c("x","tau_add","tau_obs"),
                                n.iter = 3000)
save(jags.burn_nee_SRER, file = newFilename)
rm(jags.burn_nee_SRER)

```


```{r}
## Plot the model and data time series with interval estimates

#for BART
# load the data file
newFilename <- sprintf("%s.jpg","NEE_BART_modelplot")
newFilename <- paste(graphPath, newFilename, sep="", collapse = NULL)
loadFilename <- sprintf("%s.Rdata","NEE_BART_JAGS")
loadFilename <- paste(dataPath, loadFilename, sep="", collapse = NULL)
load(file = loadFilename)
time = time_BART
time.rng = c(1,length(time)) ## adjust to zoom in and out
out <- as.matrix(jags.burn_nee_BART)
rm(jags.burn_nee_BART)
x.cols <- grep("^x",colnames(out)) ## grab all columns that start with the letter x
ci <- apply(out[,x.cols],2,quantile,c(0.025,0.5,0.975)) ## 
jpeg(file = newFilename)
plot(time,ci[2,],type='n',ylim=range(nee_BART,na.rm=TRUE),ylab="BART NEE",xlim=time[time.rng])
## adjust x-axis label to be monthly if zoomed
if(diff(time.rng) < 100){
  axis.Date(1, at=seq(time[time.rng[1]],time[time.rng[2]],by='month'), format = "%Y-%m")
}
ecoforecastR::ciEnvelope(time,ci[1,],ci[3,],col=ecoforecastR::col.alpha("lightBlue",0.75))
points(time,nee_BART,pch="+",cex=0.5)
dev.off()

rm(out)


#for KONZ
newFilename <- sprintf("%s.jpg","NEE_KONZ_modelplot")
newFilename <- paste(graphPath, newFilename, sep="", collapse = NULL)
loadFilename <- sprintf("%s.Rdata","NEE_KONZ_JAGS")
loadFilename <- paste(dataPath, loadFilename, sep="", collapse = NULL)
load(file = loadFilename)
time = time_KONZ
time.rng = c(1,length(time)) ## adjust to zoom in and out
out <- as.matrix(jags.burn_nee_KONZ)
rm(jags.burn_nee_KONZ)
x.cols <- grep("^x",colnames(out)) ## grab all columns that start with the letter x
ci <- apply(out[,x.cols],2,quantile,c(0.025,0.5,0.975)) ## 
jpeg(file = newFilename)
plot(time,ci[2,],type='n',ylim=range(nee_KONZ,na.rm=TRUE),ylab="KONZ NEE",xlim=time[time.rng])
## adjust x-axis label to be monthly if zoomed
if(diff(time.rng) < 100){
  axis.Date(1, at=seq(time[time.rng[1]],time[time.rng[2]],by='month'), format = "%Y-%m")
}
ecoforecastR::ciEnvelope(time,ci[1,],ci[3,],col=ecoforecastR::col.alpha("lightBlue",0.75))
points(time,nee_KONZ,pch="+",cex=0.5)
dev.off()

rm(out)


#for OSBS
newFilename <- sprintf("%s.jpg","NEE_OSBS_modelplot")
newFilename <- paste(graphPath, newFilename, sep="", collapse = NULL)
loadFilename <- sprintf("%s.Rdata","NEE_OSBS_JAGS")
loadFilename <- paste(dataPath, loadFilename, sep="", collapse = NULL)
load(file = loadFilename)
time = time_OSBS
time.rng = c(1,length(time)) ## adjust to zoom in and out
out <- as.matrix(jags.burn_nee_OSBS)
rm(jags.burn_nee_OSBS)
x.cols <- grep("^x",colnames(out)) ## grab all columns that start with the letter x
ci <- apply(out[,x.cols],2,quantile,c(0.025,0.5,0.975)) ## 
jpeg(file = newFilename)
plot(time,ci[2,],type='n',ylim=range(nee_OSBS,na.rm=TRUE),ylab="OSBS NEE",xlim=time[time.rng])
## adjust x-axis label to be monthly if zoomed
if(diff(time.rng) < 100){
  axis.Date(1, at=seq(time[time.rng[1]],time[time.rng[2]],by='month'), format = "%Y-%m")
}
ecoforecastR::ciEnvelope(time,ci[1,],ci[3,],col=ecoforecastR::col.alpha("lightBlue",0.75))
points(time,nee_OSBS,pch="+",cex=0.5)
dev.off()

rm(out)


#for SRER
newFilename <- sprintf("%s.jpg","NEE_SRER_modelplot")
newFilename <- paste(graphPath, newFilename, sep="", collapse = NULL)
loadFilename <- sprintf("%s.Rdata","NEE_SRER_JAGS")
loadFilename <- paste(dataPath, loadFilename, sep="", collapse = NULL)
load(file = loadFilename)
time = time_SRER
time.rng = c(1,length(time)) ## adjust to zoom in and out
out <- as.matrix(jags.burn_nee_SRER)
rm(jags.burn_nee_SRER)
x.cols <- grep("^x",colnames(out)) ## grab all columns that start with the letter x
ci <- apply(out[,x.cols],2,quantile,c(0.025,0.5,0.975)) ## 
jpeg(file = newFilename)
plot(time,ci[2,],type='n',ylim=range(nee_SRER,na.rm=TRUE),ylab="SRER NEE",xlim=time[time.rng])
## adjust x-axis label to be monthly if zoomed
if(diff(time.rng) < 100){
  axis.Date(1, at=seq(time[time.rng[1]],time[time.rng[2]],by='month'), format = "%Y-%m")
}
ecoforecastR::ciEnvelope(time,ci[1,],ci[3,],col=ecoforecastR::col.alpha("lightBlue",0.75))
points(time,nee_SRER,pch="+",cex=0.5)
dev.off()

rm(out)

```

