---
title: "02C_HistoricalFitting_VSWC"
author: "Nia Bartolucci; Cameron Reimer; Kangjoon Cho; Zhenpeng Zuo"
date: "3/25/2021"
output: html_document
---

```{r}
## Package check and load

#install.packages("tidyverse")
#install.packages("readr")
library(tidyverse)
library(readr)
library(rjags)
library(daymetr)
source("/Users/niabartolucci/Dropbox/My Mac (Nia’s MacBook Pro)/Desktop/Classes Spring 2021/Ecological Forecasting/EF_Activities/ecoforecastR/R/utils.R")
#remotes::install_github("EcoForecast/ecoforecastR",force=TRUE)
```

```{r}
# If you need run data download
###source('01A_Targetdownload.R')

# definition for PATH
basePath <- getwd() 
graphPath <- paste0(basePath,"/graph/")
dataPath <- paste0(basePath,"/data/")

# load the data file [30 min Target data]
loadFilename <- sprintf("%s.Rdata","Target_30min")
loadFilename <- paste(dataPath, loadFilename, sep="", collapse = NULL)
load(file = loadFilename)

# load the data file [daily Target data]
loadFilename <- sprintf("%s.Rdata","Target_daily")
loadFilename <- paste(dataPath, loadFilename, sep="", collapse = NULL)
load(file = loadFilename)

# define site names
site_names <- c("BART","KONZ","OSBS","SRER")

```

```{r}

#Subset Data 

Target_30min_BART = subset(Target_30min, siteID == 'BART')
Target_30min_KONZ = subset(Target_30min, siteID == 'KONZ')
Target_30min_OSBS = subset(Target_30min, siteID == 'OSBS')
Target_30min_SRER = subset(Target_30min, siteID == 'SRER')

time_BART = as.Date(Target_30min_BART$time)
time_KONZ = as.Date(Target_30min_KONZ$time)
time_OSBS = as.Date(Target_30min_OSBS$time)
time_SRER = as.Date(Target_30min_SRER$time)

Target_daily_BART = subset(Target_daily, siteID == 'BART')
Target_daily_KONZ = subset(Target_daily, siteID == 'KONZ')
Target_daily_OSBS = subset(Target_daily, siteID == 'OSBS')
Target_daily_SRER = subset(Target_daily, siteID == 'SRER')

time_daily_BART = as.Date(Target_daily_BART$time)
time_daily_KONZ = as.Date(Target_daily_KONZ$time)
time_daily_OSBS = as.Date(Target_daily_OSBS$time)
time_daily_SRER = as.Date(Target_daily_SRER$time)

vswc_BART = Target_30min_BART$vswc
vswc_KONZ = Target_30min_KONZ$vswc
vswc_OSBS = Target_30min_OSBS$vswc
vswc_SRER = Target_30min_SRER$vswc

```

```{r}
RandomWalk = "
model{
  #### Data Model
  for(t in 1:n){
    y[t] ~ dnorm(x[t],tau_obs)
  }
  #### Process Model
  for(t in 2:n){
    Dnew[t]=x[t-1] + PrecipSens*t
    #Dnew[t]=rho*x[t-1] + PrecipSens*Precipdata[t]
    x[t]~dnorm(Dnew[t],tau_add)
  }
  #### Priors
  x[1] ~ dnorm(x_ic,tau_ic)
  tau_obs ~ dgamma(a_obs,r_obs)
  tau_add ~ dgamma(a_add,r_add)
  PrecipSens ~ dgamma(.5,.5)
  #rho ~ dgamma(.5,.5)
}
"
```

```{r}
#Set Initial Conditions 
x_ic_vswc = 0
tau_ic_vswc = 10 
#PrecipSens = .5

data_vswc_BART <- list(y=vswc_BART,n=length(vswc_BART),x_ic= x_ic_vswc,tau_ic=tau_ic_vswc, a_obs=1,r_obs=1,a_add=1,r_add=1)
data_vswc_KONZ <- list(y=vswc_KONZ,n=length(vswc_KONZ),x_ic= x_ic_vswc,tau_ic=tau_ic_vswc, a_obs=1,r_obs=1,a_add=1,r_add=1)
data_vswc_OSBS <- list(y=vswc_OSBS,n=length(vswc_OSBS),x_ic= x_ic_vswc,tau_ic=tau_ic_vswc, a_obs=1,r_obs=1,a_add=1,r_add=1)
data_vswc_SRER <- list(y=vswc_SRER,n=length(vswc_SRER),x_ic= x_ic_vswc,tau_ic=tau_ic_vswc, a_obs=1,r_obs=1,a_add=1,r_add=1)
```

```{r}
#Set inits 

#vswc
nchain = 3
init_vswc_BART <- list()
init_vswc_KONZ <- list()
init_vswc_OSBS <- list()
init_vswc_SRER <- list()
y_BART = vswc_BART 
y_KONZ = vswc_KONZ
y_OSBS = vswc_OSBS
y_SRER = vswc_SRER
y_BART = na.omit(y_BART)
y_KONZ = na.omit(y_KONZ)
y_OSBS = na.omit(y_OSBS)
y_SRER = na.omit(y_SRER)
for(i in 1:nchain){
  y.samp = sample(y_BART,length(y_BART),replace=TRUE)
  init_vswc_BART[[i]] <- list(tau_add=1/var(diff(y.samp)),tau_obs=5/var(y.samp))
  y.samp = sample(y_KONZ,length(y_KONZ),replace=TRUE)
  init_vswc_KONZ[[i]] <- list(tau_add=1/var(diff(y.samp)),tau_obs=5/var(y.samp))
  y.samp = sample(y_OSBS,length(y_OSBS),replace=TRUE)
  init_vswc_OSBS[[i]] <- list(tau_add=1/var(diff(y.samp)),tau_obs=5/var(y.samp))
  y.samp = sample(y_SRER,length(y_SRER),replace=TRUE)
  init_vswc_SRER[[i]] <- list(tau_add=1/var(diff(y.samp)),tau_obs=5/var(y.samp))
}
```


```{r}
#BART Model Runs

j.model_vswc_BART   <- jags.model (file = textConnection(RandomWalk),
                             data = data_vswc_BART,
                             inits = init_vswc_BART,
                             n.chains = 3)

```

```{r}
#MCMC diagnostics & Burn-in test
jags.out_vswc_BART <- coda.samples (model = j.model_vswc_BART,
                            variable.names = c("tau_add","tau_obs","PrecipSens"),
                                n.iter = 10)


plot(jags.out_vswc_BART)


```

```{r}
## remove burn-in and save MCMC output

jags.out_vswc_BART   <- coda.samples (model = j.model_vswc_BART,
                            variable.names = c("x","tau_add","tau_obs","PrecipSens"),
                                n.iter = 2000)


```



```{r}
## Plot the model and data time series with interval estimates

#for BART
time = time_BART
time.rng = c(1,length(time)) ## adjust to zoom in and out
out <- as.matrix(jags.out_vswc_BART)
#x.cols <- grep("^x",colnames(out)) ## grab all columns that start with the letter x
ci <- apply(out,2,quantile,c(0.025,0.5,0.975)) ## 
plot(time,ci[2,],type='n',ylim=range(vswc_BART,na.rm=TRUE),ylab="BART VSWC",xlim=time[time.rng])
## adjust x-axis label to be monthly if zoomed
if(diff(time.rng) < 100){
  axis.Date(1, at=seq(time[time.rng[1]],time[time.rng[2]],by='month'), format = "%Y-%m")
}
ciEnvelope(time,ci[1,],ci[3,],col=col.alpha("lightBlue",0.75))
points(time,vswc_BART,pch="+",cex=0.5)



```