---
title: "03B_initial_forecast_LE"
author: "Nia Bartolucci; Cameron Reimer; Kangjoon Cho; Zhenpeng Zuo"
date: "4/14/2021"
output: html_document
---

```{r}
## Package check and load

#install.packages("tidyverse")
#install.packages("readr")
library(tidyverse)
library(readr)
library(rjags)
library(rnoaa)
library(daymetr)
library(ecoforecastR)
#source("/Users/niabartolucci/Dropbox/My Mac (Nia’s MacBook Pro)/Desktop/Classes Spring 2021/Ecological Forecasting/EF_Activities/ecoforecastR/R/utils.R")

#remotes::install_github("EcoForecast/ecoforecastR",force=TRUE)
```

```{r}
# If you need run data download
###source('01A_Targetdownload.R')

# definition for PATH
basePath <- getwd() 
graphPath <- paste0(basePath,"/graph/")
dataPath <- paste0(basePath,"/data/")

# load the data file [30 min Target data]
loadFilename <- sprintf("%s.Rdata","Target_30min")
loadFilename <- paste(dataPath, loadFilename, sep="", collapse = NULL)
load(file = loadFilename)

loadFilename <- sprintf("%s.Rdata","Radiance")
loadFilename <- paste(dataPath, loadFilename, sep="", collapse = NULL)
load(file = loadFilename)

loadFilename <- sprintf("%s.Rdata","Air_Temperature")
loadFilename <- paste(dataPath, loadFilename, sep="", collapse = NULL)
load(file = loadFilename)

loadFilename <- sprintf("%s.Rdata","Precipitation")
loadFilename <- paste(dataPath, loadFilename, sep="", collapse = NULL)
load(file = loadFilename)

swlw_data = swlw[["SLRNR_30min"]]
rm(swlw)

precip_data = precip[["PRIPRE_30min"]]
rm(precip)

temp_data = Tmp[["SAAT_30min"]]
rm(Tmp)


# define site names
site_names <- c("BART","KONZ","OSBS","SRER")

```

```{r}
##subset
Target_30min_BART = subset(Target_30min, siteID == 'BART' & time >= as.POSIXct('2020-03-01 00:00', tz="UTC") & 
                                                                time < as.POSIXct('2021-03-01 00:00', tz="UTC"))
Target_30min_KONZ = subset(Target_30min, siteID == 'KONZ' & time >= as.POSIXct('2020-03-01 00:00', tz="UTC") & 
                                                                time < as.POSIXct('2021-03-01 00:00', tz="UTC"))
Target_30min_OSBS = subset(Target_30min, siteID == 'OSBS' & time >= as.POSIXct('2020-03-01 00:00', tz="UTC") & 
                                                                time < as.POSIXct('2021-03-01 00:00', tz="UTC"))
Target_30min_SRER = subset(Target_30min, siteID == 'SRER' & time >= as.POSIXct('2020-03-01 00:00', tz="UTC") & 
                                                                time < as.POSIXct('2021-03-01 00:00', tz="UTC"))


time_BART = Target_30min_BART$time
time_KONZ = Target_30min_KONZ$time
time_OSBS = Target_30min_OSBS$time
time_SRER = Target_30min_SRER$time

LE_BART = Target_30min_BART$le
LE_KONZ = Target_30min_KONZ$le
LE_OSBS = Target_30min_OSBS$le
LE_SRER = Target_30min_SRER$le

NEE_BART = Target_30min_BART$nee
NEE_KONZ =Target_30min_KONZ$nee
NEE_OSBS =Target_30min_OSBS$nee
NEE_SRER =Target_30min_SRER$nee

VSWC_BART = Target_30min_BART$vswc
VSWC_KONZ =Target_30min_KONZ$vswc
VSWC_OSBS =Target_30min_OSBS$vswc
VSWC_SRER =Target_30min_SRER$vswc


swlw_KONZ = subset(swlw_data, siteID == 'KONZ' & verticalPosition == '040' & 
                     startDateTime >= as.POSIXct('2020-03-01 00:00', tz="UTC") &
                     startDateTime < as.POSIXct('2021-03-01 00:00', tz="UTC"))

precip_KONZ = subset(precip_data, siteID == 'KONZ' & 
                     startDateTime >= as.POSIXct('2020-03-01 00:00', tz="UTC") &
                     startDateTime < as.POSIXct('2021-03-01 00:00', tz="UTC"))

temp_KONZ = subset(temp_data, siteID == 'KONZ' & verticalPosition == '010' & 
                     startDateTime >= as.POSIXct('2020-03-01 00:00', tz="UTC") &
                     startDateTime < as.POSIXct('2021-03-01 00:00', tz="UTC"))

data_03 = data.frame(time = time_KONZ, LE_obs = LE_KONZ, NEE_obs = NEE_KONZ, VSWC_obs = VSWC_KONZ)
data_03$insw = swlw_KONZ$inSWMean[match(data_03$time,swlw_KONZ$startDateTime)]
data_03$inlw = swlw_KONZ$inLWMean[match(data_03$time,swlw_KONZ$startDateTime)]
data_03$temp = temp_KONZ$tempSingleMean[match(data_03$time,temp_KONZ$startDateTime)]
data_03$precip = precip_KONZ$priPrecipBulk[match(data_03$time,precip_KONZ$startDateTime)]
```


```{r}
#Dynamic Linear Model for joint dataset

JointDLM = "
model{
  
  #### Priors
  NEE[1] ~ dnorm(NEE_ic,tau_nee_ic)
  LE[1] ~ dnorm(LE_ic,tau_le_ic)
  VSWC[1] ~ dnorm(VSWC_ic,tau_vswc_ic)
  
  tau_nee_obs ~ dgamma(a_nee_obs,r_nee_obs)
  tau_nee_add ~ dgamma(a_nee_add,r_nee_add)
  tau_le_obs ~ dgamma(a_le_obs,r_le_obs)
  tau_le_add ~ dgamma(a_le_add,r_le_add)
  tau_vswc_obs ~ dgamma(a_vswc_obs,r_vswc_obs)
  tau_vswc_add ~ dgamma(a_vswc_add,r_vswc_add)
  
  #### Fixed effect
  
  beta_NEE ~ dnorm(0,0.001)
  beta_LE ~ dnorm(0,0.001)
  beta_VSWC ~ dnorm(0,0.001)
  beta_NL ~ dnorm(0,0.001)
  beta_NV ~ dnorm(0,0.001)
  beta_LN ~ dnorm(0,0.001)
  beta_LV ~ dnorm(0,0.001)
  beta_VN ~ dnorm(0,0.001)
  beta_VL ~ dnorm(0,0.001)
  beta_NEEI ~ dnorm(0,0.001)
  beta_LEI ~ dnorm(0,0.001)
  beta_VSWCI ~ dnorm(0,0.001)
  beta_sw1 ~ dnorm(0,0.001)
  beta_sw2 ~ dnorm(0,0.001)
  beta_lw ~ dnorm(0,0.001)
  beta_temp ~ dnorm(0,0.001)
  beta_precip ~ dnorm(0,0.001)
  
  for(i in 1:3){
  muXfI[i] ~ dnorm(0,0.001)
  tauXfI[i] ~ dgamma(0.01,0.01)
  }
  for(j in 1:4){
  muXfC[j] ~ dnorm(0,0.001)
  tauXfC[j] ~ dgamma(0.01,0.01)
  }
  
  #### Data Model
  for(t in 1:n){
    NEE_obs[t] ~ dnorm(NEE[t],tau_nee_obs)
    LE_obs[t] ~ dnorm(LE[t],tau_le_obs)
    VSWC_obs[t] ~ dnorm(VSWC[t],tau_vswc_obs)
    XfI[t,1] ~ dnorm(muXfI[1],tauXfI[1])
    XfI[t,2] ~ dnorm(muXfI[2],tauXfI[2])
    XfI[t,3] ~ dnorm(muXfI[3],tauXfI[3])
    XfC[t,1] ~ dnorm(muXfC[1],tauXfC[1])
    XfC[t,2] ~ dnorm(muXfC[2],tauXfC[2])
    XfC[t,3] ~ dnorm(muXfC[3],tauXfC[3])
    XfC[t,4] ~ dnorm(muXfC[4],tauXfC[4])
  }
  
  #### Process Model
  for(t in 2:n){
    mu_nee[t] <- NEE[t-1] + beta_NEE * NEE[t-1] + beta_NL * LE[t-1] + beta_NV * VSWC[t-1] + beta_NEEI * XfI[t,1] + beta_sw1 * XfC[t,1] + beta_temp * XfC[t,3]
    mu_le[t] <- LE[t-1] + beta_LE * LE[t-1] + beta_LN * NEE[t-1] + beta_LV * VSWC[t-1] + beta_LEI * XfI[t,2] + beta_sw2 * XfC[t,1] + beta_lw * XfC[t,2]
    mu_vswc[t] <- VSWC[t-1] + beta_VSWC * VSWC[t-1] + beta_VN * NEE[t-1] + beta_VL * LE[t-1] + beta_VSWCI * XfI[t,3] + beta_precip * XfC[t,4]
    
    NEE[t]~dnorm(mu_nee[t],tau_nee_add)
    LE[t]~dnorm(mu_le[t],tau_le_add)
    VSWC[t]~dnorm(mu_vswc[t],tau_vswc_add)
  }
  
}
"

```

```{r}
XfI = matrix(1,nrow = length(time_KONZ), ncol = 3)
tmp = data_03[,5:8]
XfC = matrix(NA, nrow = length(time_KONZ), ncol = 4)
for(i in 1:4){
  XfC[,i] = tmp[,i]
}

data_joint<-list(NEE_obs=data_03$NEE_obs,LE_obs=data_03$LE_obs,VSWC_obs=data_03$VSWC_obs, n=length(time_KONZ),
            NEE_ic = 0, LE_ic = 0, VSWC_ic = 0, tau_nee_ic = 0.00001, tau_le_ic = 0.00001, tau_vswc_ic = 0.00001,
            a_nee_obs=3, r_nee_obs=1, a_nee_add=3, r_nee_add=1,
            a_le_obs=0.5, r_le_obs=1, a_le_add=0.1, r_le_add=0.1,
            a_vswc_obs=0.1, r_vswc_obs=0.1, a_vswc_add=0.1, r_vswc_add=0.1,
            XfI = XfI, XfC = XfC)

```

```{r}
#Set inits 

#vswc
nchain = 3
init_joint <- list()

y_NEE = data_03$NEE_obs 
y_LE = data_03$LE_obs
y_VSWC = data_03$VSWC_obs
y_NEE = na.omit(y_NEE)
y_LE = na.omit(y_LE)
y_VSWC = na.omit(y_VSWC)

for(i in 1:nchain){
  y.samp_NEE = sample(y_NEE,length(y_NEE),replace=TRUE)
  y.samp_LE = sample(y_LE,length(y_LE),replace=TRUE)
  y.samp_VSWC = sample(y_VSWC,length(y_VSWC),replace=TRUE)
  init_joint[[i]] <- list(tau_nee_add=1/var(diff(y.samp_NEE)),tau_nee_obs=5/var(y.samp_NEE),
                          tau_le_add=1/var(diff(y.samp_LE)),tau_le_obs=5/var(y.samp_LE),
                          tau_vswc_add=1/var(diff(y.samp_VSWC)),tau_vswc_obs=5/var(y.samp_VSWC))
}
```

```{r}

#Now that we've defined the model, the data, and the initialization, we need to send all this info to JAGS, which will return the JAGS model object.

j.model_joint   <- jags.model (file = textConnection(JointDLM),
                            data = data_joint,
                            inits = init_joint,
                            n.chains = 3)

```

```{r}
variable_names = c("NEE",   "LE",  "VSWC",
                   "tau_nee_obs", "tau_nee_add", "tau_le_obs", "tau_le_add", "tau_vswc_obs", "tau_vswc_add",
                   "beta_NEE", "beta_LE", "beta_VSWC", "beta_NEEI", "beta_LEI", "beta_VSWCI", 
                   "beta_NL", "beta_NV", "beta_LN", "beta_LV", "beta_VN", "beta_VL", 
                   "beta_sw1", "beta_sw2", "beta_lw", "beta_temp", "beta_precip")

```


```{r}
#MCMC diagnostics & Burn-in test
jags.out_joint <- coda.samples (model = j.model_joint,
                            variable.names = variable_names,
                                n.iter = 20000, thin=20)


```


```{r}
## split output

joint_out = list(params=NULL,predict=NULL,model=JointDLM,data=data_joint)
mfit = as.matrix(jags.out_joint,chains=TRUE)
pred.cols = union(grep("LE[",colnames(mfit),fixed=TRUE),grep("NEE[",colnames(mfit),fixed=TRUE))
pred.cols = union(pred.cols,grep("VSWC[",colnames(mfit),fixed=TRUE))
chain.col = which(colnames(mfit)=="CHAIN")
joint_out$predict = mat2mcmc.list(mfit[,c(chain.col,pred.cols)])
joint_out$params   = mat2mcmc.list(mfit[,-pred.cols])

```


```{r}
# burn-in test (covergence : OK / Gelman plot : >260 OK)
#newFilename <- sprintf("%s.pdf","joint_KONZ_traceplot")
#newFilename <- paste(graphPath, newFilename, sep="", collapse = NULL)
#pdf(file = newFilename)
plot(joint_out$params)
#dev.off()

#newFilename <- sprintf("%s.pdf","joint_KONZ_gelmanplot")
#newFilename <- paste(graphPath, newFilename, sep="", collapse = NULL)
#pdf(file = newFilename)
BGR_params <- gelman.plot(joint_out$params)
#dev.off()

BGR_params$shrink > 1.1
gelman.diag(joint_out$params)

newFilename <- sprintf("%s.Rdata","joint_3rd_beforeburn")
newFilename <- paste(dataPath, newFilename, sep="", collapse = NULL)
save(joint_out, file = newFilename)

```




```{r}
# burn-in removal

joint_out$params <- window(joint_out$params,start=500)
joint_out$predict <- window(joint_out$predict,start=500)

summary(joint_out$params)
cor(as.matrix(joint_out$params))
pairs(as.matrix(joint_out$params))
time = data_03$time
time.rng = c(1,length(time))

newFilename <- sprintf("%s.Rdata","joint_3rd_burn")
newFilename <- paste(dataPath, newFilename, sep="", collapse = NULL)
save(joint_out, file = newFilename)

```

```{r}
## Plot the model and data time series with interval estimates
rm(jags.out_joint, joint_out)

#for KONZ
# load the data file
loadFilename <- sprintf("%s.Rdata","joint_3rd_burn")
loadFilename <- paste(dataPath, loadFilename, sep="", collapse = NULL)
load(file = loadFilename)

newFilename <- sprintf("%s.jpg","joint_modelplot_DLM_KONZ_NEE")
newFilename <- paste(graphPath, newFilename, sep="", collapse = NULL)

time = time_KONZ
time.rng = c(1,length(time)) ## adjust to zoom in and out
out <- as.matrix(joint_out$predict)
rm()
x.cols <- grep("^NEE",colnames(out)) ## grab all columns that start with the letter x
ci <- apply(out[,x.cols],2,quantile,c(0.025,0.5,0.975)) ## 
jpeg(file = newFilename)
plot(time,ci[2,],type='n',ylim=range(NEE_KONZ,na.rm=TRUE),ylab="KONZ NEE",xlim=time[time.rng])
## adjust x-axis label to be monthly if zoomed
if(diff(time.rng) < 100){
  axis.Date(1, at=seq(time[time.rng[1]],time[time.rng[2]],by='month'), format = "%Y-%m")
}
#ecoforecastR::ciEnvelope(time,ci[1,],ci[3,],col=ecoforecastR::col.alpha("lightBlue",0.75))
ciEnvelope(time,ci[1,],ci[3,],col=col.alpha("lightBlue",0.75))
points(time,NEE_KONZ,pch="+",cex=0.5)
dev.off()

# load the data file
newFilename <- sprintf("%s.jpg","joint_modelplot_DLM_KONZ_LE")
newFilename <- paste(graphPath, newFilename, sep="", collapse = NULL)

time = time_KONZ
time.rng = c(1,length(time)) ## adjust to zoom in and out
out <- as.matrix(joint_out$predict)
rm()
x.cols <- grep("^LE",colnames(out)) ## grab all columns that start with the letter x
ci <- apply(out[,x.cols],2,quantile,c(0.025,0.5,0.975)) ## 
jpeg(file = newFilename)
plot(time,ci[2,],type='n',ylim=range(LE_KONZ,na.rm=TRUE),ylab="KONZ LE",xlim=time[time.rng])
## adjust x-axis label to be monthly if zoomed
if(diff(time.rng) < 100){
  axis.Date(1, at=seq(time[time.rng[1]],time[time.rng[2]],by='month'), format = "%Y-%m")
}
#ecoforecastR::ciEnvelope(time,ci[1,],ci[3,],col=ecoforecastR::col.alpha("lightBlue",0.75))
ciEnvelope(time,ci[1,],ci[3,],col=col.alpha("lightBlue",0.75))
points(time,LE_KONZ,pch="+",cex=0.5)
dev.off()

# load the data file

newFilename <- sprintf("%s.jpg","joint_modelplot_DLM_KONZ_VSWC")
newFilename <- paste(graphPath, newFilename, sep="", collapse = NULL)

time = time_KONZ
time.rng = c(1,length(time)) ## adjust to zoom in and out
out <- as.matrix(joint_out$predict)
rm()
x.cols <- grep("^VSWC",colnames(out)) ## grab all columns that start with the letter x
ci <- apply(out[,x.cols],2,quantile,c(0.025,0.5,0.975)) ## 
jpeg(file = newFilename)
plot(time,ci[2,],type='n',ylim=range(VSWC_KONZ,na.rm=TRUE),ylab="KONZ VSWC",xlim=time[time.rng])
## adjust x-axis label to be monthly if zoomed
if(diff(time.rng) < 100){
  axis.Date(1, at=seq(time[time.rng[1]],time[time.rng[2]],by='month'), format = "%Y-%m")
}
#ecoforecastR::ciEnvelope(time,ci[1,],ci[3,],col=ecoforecastR::col.alpha("lightBlue",0.75))
ciEnvelope(time,ci[1,],ci[3,],col=col.alpha("lightBlue",0.75))
points(time,VSWC_KONZ,pch="+",cex=0.5)
dev.off()


rm(out)

#newFilename <- sprintf("%s.jpg","joint_modelplot_DLM_KONZ_VSWC")
#newFilename <- paste(graphPath, newFilename, sep="", collapse = NULL)

time = time_KONZ
time.rng = c(1,length(time)) ## adjust to zoom in and out
out <- as.matrix(joint_out$predict)
rm()
x.cols <- grep("^NEE",colnames(out)) ## grab all columns that start with the letter x
ci <- apply(out[,x.cols],2,quantile,c(0.025,0.5,0.975)) ## 
#jpeg(file = newFilename)
plot(time,ci[2,],type='n',ylim=range(NEE_KONZ,na.rm=TRUE),ylab="KONZ NEE",xlim=time[time.rng])
## adjust x-axis label to be monthly if zoomed
if(diff(time.rng) < 100){
  axis.Date(1, at=seq(time[time.rng[1]],time[time.rng[2]],by='month'), format = "%Y-%m")
}
#ecoforecastR::ciEnvelope(time,ci[1,],ci[3,],col=ecoforecastR::col.alpha("lightBlue",0.75))
ciEnvelope(time,ci[1,],ci[3,],col=col.alpha("lightBlue",0.75))
points(time,NEE_KONZ,pch="+",cex=0.5)
#dev.off()

#newFilename <- sprintf("%s.jpg","joint_modelplot_DLM_KONZ_VSWC")
#newFilename <- paste(graphPath, newFilename, sep="", collapse = NULL)

time = time_KONZ
time.rng = c(1,length(time)) ## adjust to zoom in and out
out <- as.matrix(joint_out$predict)
rm()
x.cols <- grep("^LE",colnames(out)) ## grab all columns that start with the letter x
ci <- apply(out[,x.cols],2,quantile,c(0.025,0.5,0.975)) ## 
#jpeg(file = newFilename)
plot(time,ci[2,],type='n',ylim=range(out[,x.cols],na.rm=TRUE),ylab="KONZ LE",xlim=time[time.rng])
## adjust x-axis label to be monthly if zoomed
if(diff(time.rng) < 100){
  axis.Date(1, at=seq(time[time.rng[1]],time[time.rng[2]],by='month'), format = "%Y-%m")
}
#ecoforecastR::ciEnvelope(time,ci[1,],ci[3,],col=ecoforecastR::col.alpha("lightBlue",0.75))
ciEnvelope(time,ci[1,],ci[3,],col=col.alpha("lightBlue",0.75))
points(time,LE_KONZ,pch="+",cex=0.5)
#dev.off()



#newFilename <- sprintf("%s.jpg","joint_modelplot_DLM_KONZ_VSWC")
#newFilename <- paste(graphPath, newFilename, sep="", collapse = NULL)

time = time_KONZ
time.rng = c(1,length(time)) ## adjust to zoom in and out
out <- as.matrix(joint_out$predict)
x.cols <- grep("^VSWC",colnames(out)) ## grab all columns that start with the letter x
ci <- apply(out[,x.cols],2,quantile,c(0.025,0.5,0.975)) ## 
#jpeg(file = newFilename)
plot(time,ci[2,],type='n',ylim=range(VSWC_KONZ,na.rm=TRUE),ylab="KONZ VSWC",xlim=time[time.rng])
## adjust x-axis label to be monthly if zoomed
if(diff(time.rng) < 100){
  axis.Date(1, at=seq(time[time.rng[1]],time[time.rng[2]],by='month'), format = "%Y-%m")
}
#ecoforecastR::ciEnvelope(time,ci[1,],ci[3,],col=ecoforecastR::col.alpha("lightBlue",0.75))
ciEnvelope(time,ci[1,],ci[3,],col=col.alpha("lightBlue",0.75))
points(time,VSWC_KONZ,pch="+",cex=0.5)
#dev.off()


rm(out)


```

```{r}

# Manipulate above code just freely #########################################
############################################### Below code is under revision

```


```{r}
#NOAA data load
# Download NOAA climate forecasts (hourly) and downsample to daily scale
source("00B_NOAAconversion.R")

for (S in site_names){
  download_noaa_files_s3(siteID = S, 
                         date = "2021-03-01", 
                         cycle = "00", 
                         local_directory <- paste0(basePath,"/drivers/"))
}
NOAA_Driver = noaa_gefs_read(paste0(basePath,"/drivers/noaa/NOAAGEFS_1hr"), "2021-03-01", "00", "KONZ")

predict_time = subset(NOAA_Driver, ensemble==1)
predict_time = predict_time$time

## Driver data conversion

sw_driver = subset(NOAA_Driver, ensemble!=0)
sw_driver = sw_driver$surface_downwelling_shortwave_flux_in_air
sw_driver = matrix(sw_driver, nrow=30 ,byrow = TRUE)

lw_driver = subset(NOAA_Driver, ensemble!=0)
lw_driver = lw_driver$surface_downwelling_longwave_flux_in_air
lw_driver = matrix(lw_driver, nrow=30 ,byrow = TRUE)

sw_driver_gf = matrix(0, nrow=30, ncol = 1681)
lw_driver_gf = matrix(0, nrow=30, ncol = 1681)

## filling gap (average)
for(i in 1:840){
  sw_driver_gf[,2*i-1]=sw_driver[,i]
  sw_driver_gf[,2*i]=(sw_driver[,i]+sw_driver[,i+1])/2
  lw_driver_gf[,2*i-1]=lw_driver[,i]
  lw_driver_gf[,2*i]=(lw_driver[,i]+lw_driver[,i+1])/2
}
sw_driver_gf[,1681]=sw_driver[,841]
lw_driver_gf[,1681]=lw_driver[,841]

```


```{r}

loadFilename <- sprintf("%s.Rdata","joint_3rd_burn")
loadFilename <- paste(dataPath, loadFilename, sep="", collapse = NULL)
load(file = loadFilename)

## Forward Simulation
### settings
Nmc = 1000         ## set number of Monte Carlo draws
N.cols <- c("red","green","blue") ## set colors
trans <- 0.8       ## set transparancy
time = 1:length(time_BART)+1681    ## total time (1yr + 35 days)
time1 = 1:length(time_BART)       ## calibration period
time2 = (length(time_BART)+1):(length(time_BART)+1681)   ## forecast period
timeN_predict = length(time2)
tmp = matrix(0,1,length(time))
#ylim = c(-500,700)
```


```{r}
plot.run <- function(){
  plot(time,tmp,type='n',ylim=range(NEE_KONZ,na.rm=TRUE),ylab="NEE")
  ecoforecastR::ciEnvelope(time1,ci[1,],ci[3,],col=col.alpha("lightBlue",0.6))
  lines(time1,ci[2,],col="blue")
  points(time1,NEE_BART)
}
```
```{r,echo=FALSE}
out <- as.matrix(joint_out$predict)
x.cols <- grep("^NEE",colnames(out)) ## grab all columns that start with the letter x
ci <- apply(out[,x.cols],2,quantile,c(0.025,0.5,0.975)) 
plot.run()
```


```{r}
##` @param IC    Initial Conditions
##` @param r     Intrinsic growth rate
##` @param Kg    Across-site ('global') mean carrying capacity
##` @param alpha Site random effect
##` @param beta  Slope of precipitation effect on K
##` @param ppt   Precipitation forecast
##` @param Q     Process error (default = 0 for deterministic runs)
##` @param n     Size of Monte Carlo ensemble
forecastNEE <- function(IC,betaIntercept,betaX,betainlw,betainsw,sw,lw,Q=0,n=Nmc){
  N <- matrix(NA,n,timeN_predict)  ## storage
  Nprev <- IC           ## initialize
  for(t in 1:timeN_predict){
    mu = (1+betaX)*Nprev + betaIntercept + (betainsw*sw[,t]) + (betainlw*lw[,t])
    N[,t] <- rnorm(n,mu,Q)                         ## predict next step
    Nprev <- N[,t]                                  ## update IC
  }
  return(N)
}

forecastLE <- function(IC,betaIntercept,betaX,betainlw,betainsw,sw,lw,Q=0,n=Nmc){
  N <- matrix(NA,n,timeN_predict)  ## storage
  Nprev <- IC           ## initialize
  for(t in 1:timeN_predict){
    mu = (1+betaX)*Nprev + betaIntercept + (betainsw*sw[,t]) + (betainlw*lw[,t])
    N[,t] <- rnorm(n,mu,Q)                         ## predict next step
    Nprev <- N[,t]                                  ## update IC
  }
  return(N)
}

forecastVSWC <- function(IC,betaIntercept,betaX,betainlw,betainsw,sw,lw,Q=0,n=Nmc){
  N <- matrix(NA,n,timeN_predict)  ## storage
  Nprev <- IC           ## initialize
  for(t in 1:timeN_predict){
    mu = (1+betaX)*Nprev + betaIntercept + (betainsw*sw[,t]) + (betainlw*lw[,t])
    N[,t] <- rnorm(n,mu,Q)                         ## predict next step
    Nprev <- N[,t]                                  ## update IC
  }
  return(N)
}
```

```{r}

## calculate mean of all inputs
sw.mean <- matrix(apply(sw_driver_gf,2,mean),1,timeN_predict) ## driver
lw.mean <- matrix(apply(lw_driver_gf,2,mean),1,timeN_predict)
## parameters
params_mat <- as.matrix(params)
param.mean <- apply(params_mat,2,mean)
## initial conditions
IC <- as.matrix(predict)

##Deterministic prediction
N.det <- forecastN(IC=mean(IC[,"x[17520]"]),
                   betaIntercept=param.mean["betaIntercept"],
                   betaX=param.mean["betaX"],
                   betainlw=param.mean["betainlw"],
                   betainsw=param.mean["betainsw"],
                   sw=sw.mean,
                   lw=lw.mean,
                   Q=0,  ## process error off
                   n=1)

## Plot run
plot.run()
lines(time2,N.det,col="purple",lwd=3)

```

```{r}
## Monte Carlo Error Propagation
Nmc = 1000
#@ sample parameter rows from previous analysis
prow = sample.int(nrow(params_mat),Nmc,replace=TRUE)

N.I <- forecastN(IC=IC[prow,"x[17520]"],
                   betaIntercept=param.mean["betaIntercept"],
                   betaX=param.mean["betaX"],
                   betainlw=param.mean["betainlw"],
                   betainsw=param.mean["betainsw"],
                   sw=sw.mean,
                   lw=lw.mean,
                   Q=0,  ## process error off
                   n=Nmc)

## Plot run
plot.run()
N.I.ci = apply(N.I,2,quantile,c(0.025,0.5,0.975),na.rm=TRUE)
ecoforecastR::ciEnvelope(time2,N.I.ci[1,],N.I.ci[3,],col=col.alpha(N.cols[1],trans))
lines(time2,N.I.ci[2,],lwd=0.5)



```


```{r}
##Parameter Uncertainty

N.IP <- forecastN(IC=IC[prow,"x[17520]"],
                   betaIntercept=params_mat[prow,"betaIntercept"],
                   betaX=params_mat[prow,"betaX"],
                   betainlw=params_mat[prow,"betainlw"],
                   betainsw=params_mat[prow,"betainsw"],
                   sw=sw.mean,
                   lw=lw.mean,
                   Q=0,  ## process error off
                   n=Nmc)

## Plot run
plot.run()
N.IP.ci = apply(N.IP,2,quantile,c(0.025,0.5,0.975),na.rm=TRUE)
ecoforecastR::ciEnvelope(time2,N.IP.ci[1,],N.IP.ci[3,],col=col.alpha(N.cols[2],trans))
ecoforecastR::ciEnvelope(time2,N.I.ci[1,],N.I.ci[3,],col=col.alpha(N.cols[1],trans))
lines(time2,N.I.ci[2,],lwd=0.5)

```

```{r}
##Driver Uncertainty
#sample driver rows
drow_sw = sample.int(nrow(sw_driver_gf),Nmc,replace = TRUE)
drow_lw = sample.int(nrow(lw_driver_gf),Nmc,replace = TRUE)

N.IPD <- forecastN(IC=IC[prow,"x[17520]"],
                   betaIntercept=params_mat[prow,"betaIntercept"],
                   betaX=params_mat[prow,"betaX"],
                   betainlw=params_mat[prow,"betainlw"],
                   betainsw=params_mat[prow,"betainsw"],
                   sw=sw_driver_gf[drow_sw,],
                   lw=lw_driver_gf[drow_lw,],
                   Q=0,  ## process error off
                   n=Nmc)

## Plot run
plot.run()
N.IPD.ci = apply(N.IPD,2,quantile,c(0.025,0.5,0.975),na.rm=TRUE)
ecoforecastR::ciEnvelope(time2,N.IPD.ci[1,],N.IPD.ci[3,],col=col.alpha(N.cols[3],trans))
ecoforecastR::ciEnvelope(time2,N.IP.ci[1,],N.IP.ci[3,],col=col.alpha(N.cols[2],trans))
ecoforecastR::ciEnvelope(time2,N.I.ci[1,],N.I.ci[3,],col=col.alpha(N.cols[1],trans))
lines(time2,N.I.ci[2,],lwd=0.5)

```

```{r}
## process error samples
#Qmc <- 1/sqrt(params_mat[prow,"Q"])  ## convert from precision to standard deviation

#N.IPDE <- forecastN(IC=IC[prow,"x[17520]"],
#                   betaIntercept=params_mat[prow,"betaIntercept"],
#                   betaX=params_mat[prow,"betaX"],
#                   betainlw=params_mat[prow,"betainlw"],
#                   betainsw=params_mat[prow,"betainsw"],
#                   sw=sw_driver_gf[drow_sw,],
#                   lw=lw_driver_gf[drow_lw,],
#                   Q=Qmc,  ## process error off
#                   n=Nmc)

## Plot run
#plot.run()
#N.IPDE.ci = apply(N.IPDE,2,quantile,c(0.025,0.5,0.975))
#ecoforecastR::ciEnvelope(time2,N.IPDE.ci[1,],N.IPDE.ci[3,],col=col.alpha(N.cols[4],trans))
#ecoforecastR::ciEnvelope(time2,N.IPD.ci[1,],N.IPD.ci[3,],col=col.alpha(N.cols[3],trans))
#ecoforecastR::ciEnvelope(time2,N.IP.ci[1,],N.IP.ci[3,],col=col.alpha(N.cols[2],trans))
#ecoforecastR::ciEnvelope(time2,N.I.ci[1,],N.I.ci[3,],col=col.alpha(N.cols[1],trans))
#lines(time2,N.I.ci[2,],lwd=0.5)
```

```{r}
## Random effect samples
#tau.mc <- 1/sqrt(params_mat[prow,"tau_site"]) ## convert from precision to std deviation
#aNew.mc <- rnorm(Nmc,0,tau.mc)            ## draw out-of-sample predictions of alpha at a new site

#N.IPDEA <- forecastN(IC=IC[prow,"x[17520]"],
#                   betaIntercept=params_mat[prow,"betaIntercept"],
#                   betaX=params_mat[prow,"betaX"],
#                   betainlw=params_mat[prow,"betainlw"],
#                   betainsw=params_mat[prow,"betainsw"],
#                   sw=sw_driver_gf[drow_sw,],
#                   lw=lw_driver_gf[drow_lw,],
#                   alpha=aNew.mc,
#                   Q=Qmc,  ## process error off
#                   n=Nmc)

## Plot run
#plot.run()
#N.IPDEA.ci = apply(N.IPDEA,2,quantile,c(0.025,0.5,0.975))
#ecoforecastR::ciEnvelope(time2,N.IPDEA.ci[1,],N.IPDEA.ci[3,],col=col.alpha(N.cols[5],trans))
#ecoforecastR::ciEnvelope(time2,N.IPDE.ci[1,],N.IPDE.ci[3,],col=col.alpha(N.cols[4],trans))
#ecoforecastR::ciEnvelope(time2,N.IPD.ci[1,],N.IPD.ci[3,],col=col.alpha(N.cols[3],trans))
#ecoforecastR::ciEnvelope(time2,N.IP.ci[1,],N.IP.ci[3,],col=col.alpha(N.cols[2],trans))
#ecoforecastR::ciEnvelope(time2,N.I.ci[1,],N.I.ci[3,],col=col.alpha(N.cols[1],trans))
#lines(time2,N.I.ci[2,],lwd=0.5)
```

```{r}
### calculation of variances
varI     <- apply(N.I,2,var)
varIP    <- apply(N.IP,2,var)
varIPD   <- apply(N.IPD,2,var)
#varIPDE  <- apply(N.IPDE,2,var)
#varIPDEA <- apply(N.IPDEA,2,var)
varMat   <- rbind(varI,varIP,varIPD)

## out-of-sample stacked area plot
V.pred.rel <- apply(varMat,2,function(x) {x/max(x)})
plot(time2,V.pred.rel[1,],ylim=c(0,1),type='n',main="Relative Variance: Out-of-Sample",ylab="Proportion of Variance",xlab="time")
ciEnvelope(time2,rep(0,ncol(V.pred.rel)),V.pred.rel[1,],col=N.cols[1])
ciEnvelope(time2,V.pred.rel[1,],V.pred.rel[2,],col=N.cols[2])
ciEnvelope(time2,V.pred.rel[2,],V.pred.rel[3,],col=N.cols[3])
ciEnvelope(time2,V.pred.rel[3,],V.pred.rel[3,],col=N.cols[3])
#ciEnvelope(time2,V.pred.rel[4,],V.pred.rel[5,],col=N.cols[5])
legend("topright",legend=c("Driver","Parameter","InitCond"),col=rev(N.cols),lty=1,lwd=3)

## in-sample stacked area plot
#V.pred.rel.in <- apply(varMat[-5,],2,function(x) {x/max(x)})
#plot(time2,V.pred.rel.in[1,],ylim=c(0,1),type='n',main="Relative Variance: In-Sample",ylab="Proportion of Variance",xlab="time")
#ciEnvelope(time2,rep(0,ncol(V.pred.rel.in)),V.pred.rel.in[1,],col=N.cols[1])
#ciEnvelope(time2,V.pred.rel.in[1,],V.pred.rel.in[2,],col=N.cols[2])
#ciEnvelope(time2,V.pred.rel.in[2,],V.pred.rel.in[3,],col=N.cols[3])
#ciEnvelope(time2,V.pred.rel.in[3,],V.pred.rel.in[4,],col=N.cols[4])
#legend("topright",legend=c("Driver","Parameter","InitCond"),col=rev(N.cols[-5]),lty=1,lwd=5)
```
